// Package transcoder orchestrates FFmpeg-based media transcoding with hardware
// acceleration detection, quality verification (VMAF/SSIM), and size-growth safety.
//
// Architecture:
//
//	The Transcoder is a FFmpeg orchestrator. It builds FFmpeg command-line arguments
//	from the StreamPlan (generated by the evaluation pipeline) and a Preset (codec,
//	quality, audio handling). Execution is async: stdout/stderr are streamed back
//	in real-time and parsed for progress frames (frame, fps, speed, time).
//
// Hardware detection:
//	On construction, DetectHardwareCapabilities() probes for NVIDIA NVENC,
//	Intel QSV, AMD AMF, and Linux VAAPI. The result is cached in hwProfile
//	so the transcoder can prefer hardware encoders when available.
//
// Transcoding pipeline:
//	1. BuildFFmpegArgs constructs the full command from StreamPlan + Preset
//	2. Execute runs FFmpeg via the proc package, streaming stderr for progress
//	3. Progress is emitted via onProgress callback to the worker pool
//	4. On completion, size comparison checks if new file is smaller (SkippedSizeGrowth)
//	5. VMAF quality verification runs if enabled (separate FFmpeg pass)
//	6. Result records encoder used, compression ratio, quality scores
//
// Size-growth safety (SkipIfLarger):
//	After transcoding, if the new file is larger than the original, the transcode
//	is aborted and the original is preserved. This prevents accidental upscales
//	or misconfigured presets from wasting space.
//
// VMAF (Video Multi-Method Assessment Fusion):
//	An optional second-pass FFmpeg command that computes a perceptual quality score
//	(0-100, higher is better). The threshold is configured (default 93.0). If VMAF
//	falls below threshold, the job is marked quality_failed even if transcoding
//	succeeded. SSIM can also be computed alongside VMAF.
package transcoder

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"mediacruncher/internal/config"
	"mediacruncher/internal/evaluation"
	"mediacruncher/internal/proc"
)

var (
	frameRegex   = regexp.MustCompile(`frame=\s*(\d+)`)
	fpsRegex     = regexp.MustCompile(`fps=\s*([\d\.]+)`)
	timeRegex    = regexp.MustCompile(`time=\s*(\d+):(\d+):([\d\.]+)`)
	speedRegex   = regexp.MustCompile(`speed=\s*([\d\.]+)x`)
	bitrateRegex = regexp.MustCompile(`bitrate=\s*([\d\.]+k?bits/s)`)
)

type TranscodeProgress struct {
	JobID       string  `json:"job_id"`
	Frames      int64   `json:"frames"`
	FPS         float64 `json:"fps"`
	Speed       float64 `json:"speed"`
	CurrentSec  float64 `json:"current_sec"`
	TotalSec    float64 `json:"total_sec"`
	Percentage  float64 `json:"percentage"`
	Bitrate     string  `json:"bitrate"`
}

type TranscodeJob struct {
	ID         string
	SourcePath string
	DestPath   string
	Plan       evaluation.StreamPlan
	Preset     config.PresetConfig
	Duration   float64
	SourceSize int64
}

type TranscodeResult struct {
	JobID              string  `json:"job_id"`
	SourcePath         string  `json:"source_path"`
	DestPath           string  `json:"dest_path"`
	EncoderUsed        string  `json:"encoder_used"`
	IsHardware         bool    `json:"is_hardware"`
	OriginalSize       int64   `json:"original_size"`
	NewSize            int64   `json:"new_size"`
	SavedBytes         int64   `json:"saved_bytes"`
	CompressionRatio   float64 `json:"compression_ratio"`
	DurationSec        float64 `json:"duration_sec"`
	VMAFScore          float64 `json:"vmaf_score"`
	SSIMScore          float64 `json:"ssim_score"`
	Verified           bool    `json:"verified"`
	VerificationReason string  `json:"verification_reason"`
	SkippedSizeGrowth  bool    `json:"skipped_size_growth"`
	FailedQualityCheck bool    `json:"failed_quality_check"`
}

// PreCheckResult captures the outcome of a pre-transcoding quality estimate.
// It is used by the worker pool to decide whether to proceed with a full encode.
type PreCheckResult struct {
	EstimatedVMAF   float64 // Average VMAF score over the pre-check segment
	EstimatedSSIM   float64 // SSIM score over the pre-check segment (0-1, higher is better)
	Passed          bool    // true if VMAF >= threshold and SSIM >= 0.90
	DurationSec     float64 // Time taken to run pre-check encode + VMAF
	EncoderUsed     string  // Encoder that produced the pre-check output
	IsHardware      bool    // Whether hardware acceleration was used
}

// PreCheck performs a rapid quality assessment on a short sample of the source file.
//
// Workflow:
//	1. Encode the first 30 seconds (or full duration if shorter) to a staging file
//	2. Run VMAF between source and pre-check output
//	3. Return PreCheckResult: if VMAF < threshold, the full encode is likely to fail
//
// This avoids wasting hours of CPU/GPU time on presets that produce poor results.
// The pre-check uses the same preset, encoder, and CRF as the full encode.
func (t *Transcoder) PreCheck(ctx context.Context, sourcePath string, preset config.PresetConfig, duration float64, sourceSize int64) (*PreCheckResult, error) {
	if duration <= 0 {
		return nil, fmt.Errorf("duration must be positive")
	}
	if duration > 30 {
		duration = 30
	}

	stagingDir := t.cfg.StagingDir
	if stagingDir == "" {
		stagingDir = filepath.Join(os.TempDir(), "mediacruncher_staging")
	}
	if err := os.MkdirAll(stagingDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create staging directory: %w", err)
	}

	start := time.Now()

	// Negotiate hardware encoder (same logic as full Encode)
	encoder, isHW := t.hwProfile.SelectEncoder(preset.VideoCodec, t.cfg.HardwareAcceleration)

	// Build FFmpeg args for pre-check encode
	args := []string{
		"-hide_banner",
		"-y",
	}

	if isHW && strings.Contains(encoder, "vaapi") {
		renderDevice := "/dev/dri/renderD128"
		if _, err := os.Stat(renderDevice); err == nil {
			args = append(args, "-init_hw_device", "vaapi=va:"+renderDevice, "-filter_hw_device", "va")
		} else {
			args = append(args, "-init_hw_device", "vaapi=va", "-filter_hw_device", "va")
		}
	}

	// First 30s only
	args = append(args, "-i", sourcePath, "-t", fmt.Sprintf("%.2f", duration))

	if len(preset.ExtraFFmpeg) > 0 {
		args = append(args, strings.Fields(preset.ExtraFFmpeg)...)
	}

	if isHW && strings.Contains(encoder, "vaapi") {
		args = append(args, "-vf", "format=nv12,hwupload")
	}

	args = append(args, "-c:v", encoder)

	crf := preset.QualityCRF
	if crf <= 0 {
		crf = 22
	}
	speed := preset.PresetSpeed
	if speed == "" {
		speed = "medium"
	}

	if isHW {
		if strings.Contains(encoder, "nvenc") {
			args = append(args, "-cq", strconv.Itoa(crf), "-preset", "p5", "-spatial-aq", "1", "-temporal-aq", "1")
		} else if strings.Contains(encoder, "qsv") {
			args = append(args, "-global_quality", strconv.Itoa(crf), "-preset", speed)
		} else if strings.Contains(encoder, "amf") {
			args = append(args, "-rc", "cqp", "-qp_p", strconv.Itoa(crf), "-qp_i", strconv.Itoa(crf))
		} else {
			args = append(args, "-crf", strconv.Itoa(crf))
		}
	} else {
		if strings.Contains(encoder, "libsvtav1") {
			args = append(args, "-crf", strconv.Itoa(crf), "-preset", "6", "-svtav1-params", "tune=0")
		} else {
			args = append(args, "-crf", strconv.Itoa(crf), "-preset", speed)
		}
	}

	// Audio passthrough
	args = append(args, "-c:a", "copy")

	ext := ".mp4"
	if filepath.Ext(sourcePath) == ".mkv" {
		ext = ".mkv"
	}
	stagedPath := filepath.Join(stagingDir, fmt.Sprintf("precheck_%d%s", time.Now().UnixNano(), ext))
	args = append(args, stagedPath)

	// Run pre-check encode
	jobCtx, cancel := context.WithTimeout(ctx, 5*time.Minute)
	defer cancel()

	_, stderr, err := proc.RunCommandWithProgress(jobCtx, nil, "ffmpeg", args...)
	_ = stderr // ignore stderr for pre-check

	if err != nil {
		_ = os.Remove(stagedPath)
		return nil, fmt.Errorf("pre-check encode failed: %w", err)
	}

	// Verify pre-check output exists
	stagedInfo, err := os.Stat(stagedPath)
	if err != nil || stagedInfo.Size() == 0 {
		return nil, fmt.Errorf("pre-check output is empty")
	}
	defer os.Remove(stagedPath)

	// Run VMAF on the pre-check segment
	var vmafScore, ssimScore float64
	if t.cfg.VMAFEnabled && duration > 0 {
		verifyRes, err := computeSegmentVMAF(ctx, sourcePath, stagedPath, 0, int(duration))
		if err == nil && verifyRes > 0 {
			vmafScore = verifyRes
		}
		ssimScore, _ = calculateFastSSIM(ctx, sourcePath, stagedPath, duration)
	}

	result := &PreCheckResult{
		EstimatedVMAF:   vmafScore,
		EstimatedSSIM:   ssimScore,
		Passed:          vmafScore >= t.cfg.VMAFThreshold && ssimScore >= 0.90,
		DurationSec:     time.Since(start).Seconds(),
		EncoderUsed:     encoder,
		IsHardware:      isHW,
	}

	return result, nil
}

type Transcoder struct {
	cfg            config.TranscoderConfig
	hwProfile      *HardwareProfile
	onProgress     func(TranscodeProgress)
	onVMAFProgress func(jobID string, current, total int)
}

func NewTranscoder(cfg config.TranscoderConfig, onProgress func(TranscodeProgress)) *Transcoder {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	hw := DetectHardwareCapabilities(ctx)

	return &Transcoder{
		cfg:        cfg,
		hwProfile:  hw,
		onProgress: onProgress,
	}
}

// SetVMAFProgressCallback sets the callback for VMAF segment verification progress.
func (t *Transcoder) SetVMAFProgressCallback(fn func(jobID string, current, total int)) {
	t.onVMAFProgress = fn
}

// GetConfig returns the current transcoder configuration.
func (t *Transcoder) GetConfig() config.TranscoderConfig {
	return t.cfg
}

// SelectPreset returns the configured preset by name, or a default fallback.
func (t *Transcoder) SelectPreset(name string) config.PresetConfig {
	for _, p := range t.cfg.Presets {
		if strings.EqualFold(p.Name, name) {
			return p
		}
	}
	if len(t.cfg.Presets) > 0 {
		return t.cfg.Presets[0]
	}
	return config.PresetConfig{
		Name:        "balanced-hevc",
		VideoCodec:  "hevc",
		QualityCRF:  22,
		PresetSpeed: "medium",
		AudioCodec:  "copy",
	}
}

// Execute performs end-to-end transcoding of a job with staging, quality verification, and atomic promotion.
func (t *Transcoder) Execute(ctx context.Context, job *TranscodeJob) (*TranscodeResult, error) {
	start := time.Now()

	// Ensure staging directory exists
	stagingDir := t.cfg.StagingDir
	if stagingDir == "" {
		stagingDir = filepath.Join(os.TempDir(), "mediacruncher_staging")
	}
	if err := os.MkdirAll(stagingDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create staging directory %s: %w", stagingDir, err)
	}

	ext := filepath.Ext(job.DestPath)
	if ext == "" {
		ext = ".mp4"
	}
	stagedPath := filepath.Join(stagingDir, fmt.Sprintf("%s_%d%s", job.ID, time.Now().UnixNano(), ext))
	defer os.Remove(stagedPath) // Clean up staging file if promotion fails or aborts

	// Negotiate hardware encoder
	encoder, isHW := t.hwProfile.SelectEncoder(job.Preset.VideoCodec, t.cfg.HardwareAcceleration)

	// Build FFmpeg argument vector
	args := []string{
		"-hide_banner",
		"-y",
	}

	if isHW && strings.Contains(encoder, "vaapi") {
		renderDevice := "/dev/dri/renderD128"
		if _, err := os.Stat(renderDevice); err == nil {
			args = append(args, "-init_hw_device", "vaapi=va:"+renderDevice, "-filter_hw_device", "va")
		} else {
			args = append(args, "-init_hw_device", "vaapi=va", "-filter_hw_device", "va")
		}
	}

	args = append(args, "-i", job.SourcePath)

	// Apply stream mapping
	if len(job.Plan.MapArgs) > 0 {
		args = append(args, job.Plan.MapArgs...)
	} else {
		args = append(args, "-map", "0")
	}

	// Configure Video Encoder
	args = append(args, "-c:v", encoder)
	if isHW && strings.Contains(encoder, "vaapi") {
		args = append(args, "-vf", "format=nv12,hwupload")
	} else {
		// Software encoders: stabilize input to yuv420p 8-bit to prevent crashes
		// on non-standard pixel formats (10-bit, 4:4:4, etc.)
		args = append(args, "-vf", "format=yuv420p")
	}
	crf := job.Preset.QualityCRF
	if crf <= 0 {
		crf = 22
	}
	speed := job.Preset.PresetSpeed
	if speed == "" {
		speed = "medium"
	}

	if isHW {
		if strings.Contains(encoder, "nvenc") {
			args = append(args, "-cq", strconv.Itoa(crf), "-preset", "p5", "-spatial-aq", "1", "-temporal-aq", "1")
		} else if strings.Contains(encoder, "qsv") {
			args = append(args, "-global_quality", strconv.Itoa(crf), "-preset", speed)
		} else if strings.Contains(encoder, "amf") {
			args = append(args, "-rc", "cqp", "-qp_p", strconv.Itoa(crf), "-qp_i", strconv.Itoa(crf))
		} else {
			args = append(args, "-crf", strconv.Itoa(crf))
		}
	} else {
		if strings.Contains(encoder, "libsvtav1") {
			args = append(args, "-crf", strconv.Itoa(crf), "-preset", "6", "-svtav1-params", "tune=0")
		} else {
			args = append(args, "-crf", strconv.Itoa(crf), "-preset", speed)
		}
	}

	// Configure Audio & Subtitles from StreamPlan
	if len(job.Plan.AudioCodecArgs) > 0 {
		args = append(args, job.Plan.AudioCodecArgs...)
	} else {
		args = append(args, "-c:a", "copy")
	}

	if len(job.Plan.SubtitleArgs) > 0 {
		args = append(args, job.Plan.SubtitleArgs...)
	} else {
		args = append(args, "-c:s", "copy")
	}

	// Optional extra flags from preset
	if job.Preset.ExtraFFmpeg != "" {
		extraParts := strings.Fields(job.Preset.ExtraFFmpeg)
		args = append(args, extraParts...)
	}

	// Muxing queue limit to prevent frame dropping in multi-stream containers
	args = append(args, "-max_muxing_queue_size", "1024", stagedPath)

	// Execute ffmpeg under OS supervisor with progress streaming
	progressCallback := func(line string) {
		if t.onProgress == nil {
			return
		}
		prog := parseProgressLine(line, job.ID, job.Duration)
		if prog != nil {
			t.onProgress(*prog)
		}
	}

	// Apply job max duration if configured
	jobCtx := ctx
	if t.cfg.MaxJobDuration > 0 {
		var cancel context.CancelFunc
		jobCtx, cancel = context.WithTimeout(ctx, t.cfg.MaxJobDuration)
		defer cancel()
	}

	_, _, err := proc.RunCommandWithProgress(jobCtx, progressCallback, "ffmpeg", args...)
	if err != nil {
		return nil, fmt.Errorf("transcode execution failed: %w", err)
	}

	// Verify output exists and has content
	stagedInfo, err := os.Stat(stagedPath)
	if err != nil || stagedInfo.Size() == 0 {
		return nil, fmt.Errorf("transcode output is empty or was not created")
	}
	newSize := stagedInfo.Size()

	// Check size growth: if transcode grew significantly and original was already compressed
	if t.cfg.SkipIfLarger && job.SourceSize > 0 && newSize >= job.SourceSize {
		// Log size growth
		res := &TranscodeResult{
			JobID:             job.ID,
			SourcePath:        job.SourcePath,
			DestPath:          job.DestPath,
			EncoderUsed:       encoder,
			IsHardware:        isHW,
			OriginalSize:      job.SourceSize,
			NewSize:           newSize,
			CompressionRatio:  float64(newSize) / float64(job.SourceSize),
			SavedBytes:        job.SourceSize - newSize,
			DurationSec:       time.Since(start).Seconds(),
			SkippedSizeGrowth: true,
			Verified:          false,
			VerificationReason: fmt.Sprintf("output file size (%d bytes) larger than source (%d bytes)", newSize, job.SourceSize),
		}
		return res, nil
	}

	// Run Quality Verification (VMAF / SSIM) if enabled
	vmafScore := 0.0
	ssimScore := 0.0
	verified := true
	reason := "quality verification skipped or passed"

	if t.cfg.VMAFEnabled && job.Duration > 5.0 {
		var vmafCb func(int, int)
		if t.onVMAFProgress != nil {
			vmafCb = func(curr, tot int) {
				t.onVMAFProgress(job.ID, curr, tot)
			}
		}
		verifyRes, err := RunQualityVerification(
			ctx,
			job.SourcePath,
			stagedPath,
			job.Duration,
			t.cfg.VMAFThreshold,
			t.cfg.VMAFSampleCount,
			t.cfg.VMAFSampleDuration,
			vmafCb,
		)
		if ctx.Err() != nil {
			_ = os.Remove(stagedPath)
			return nil, ctx.Err()
		}
		if err != nil {
			reason = fmt.Sprintf("quality verification error: %v", err)
			verified = false
		} else if verifyRes != nil {
			vmafScore = verifyRes.AverageVMAF
			ssimScore = verifyRes.SSIMScore
			verified = verifyRes.Passed
			reason = verifyRes.Reason
		}

		if !verified {
			_ = os.Remove(stagedPath)
			return &TranscodeResult{
				JobID:              job.ID,
				SourcePath:         job.SourcePath,
				DestPath:           job.DestPath,
				EncoderUsed:        encoder,
				IsHardware:         isHW,
				OriginalSize:       job.SourceSize,
				NewSize:            newSize,
				SavedBytes:         job.SourceSize - newSize,
				DurationSec:        time.Since(start).Seconds(),
				VMAFScore:          vmafScore,
				SSIMScore:          ssimScore,
				Verified:           false,
				VerificationReason: reason,
				FailedQualityCheck: true,
			}, nil
		}
	}

	if ctx.Err() != nil {
		_ = os.Remove(stagedPath)
		return nil, ctx.Err()
	}

	// Atomic promotion to final destination
	inPlace := (job.SourcePath == job.DestPath)
	if err := PromoteFile(stagedPath, job.DestPath, inPlace); err != nil {
		_ = os.Remove(stagedPath)
		return nil, fmt.Errorf("failed to promote transcoded file to destination: %w", err)
	}

	ratio := 0.0
	if job.SourceSize > 0 {
		ratio = float64(newSize) / float64(job.SourceSize)
	}

	return &TranscodeResult{
		JobID:              job.ID,
		SourcePath:         job.SourcePath,
		DestPath:           job.DestPath,
		EncoderUsed:        encoder,
		IsHardware:         isHW,
		OriginalSize:       job.SourceSize,
		NewSize:            newSize,
		SavedBytes:         job.SourceSize - newSize,
		CompressionRatio:   ratio,
		DurationSec:        time.Since(start).Seconds(),
		VMAFScore:          vmafScore,
		SSIMScore:          ssimScore,
		Verified:           verified,
		VerificationReason: reason,
		SkippedSizeGrowth:  false,
	}, nil
}

func parseProgressLine(line string, jobID string, totalDuration float64) *TranscodeProgress {
	if !strings.Contains(line, "frame=") && !strings.Contains(line, "time=") {
		return nil
	}

	prog := &TranscodeProgress{
		JobID:    jobID,
		TotalSec: totalDuration,
	}

	if m := frameRegex.FindStringSubmatch(line); len(m) >= 2 {
		prog.Frames, _ = strconv.ParseInt(m[1], 10, 64)
	}
	if m := fpsRegex.FindStringSubmatch(line); len(m) >= 2 {
		prog.FPS, _ = strconv.ParseFloat(m[1], 64)
	}
	if m := speedRegex.FindStringSubmatch(line); len(m) >= 2 {
		prog.Speed, _ = strconv.ParseFloat(m[1], 64)
	}
	if m := bitrateRegex.FindStringSubmatch(line); len(m) >= 2 {
		prog.Bitrate = m[1]
	}
	if m := timeRegex.FindStringSubmatch(line); len(m) >= 4 {
		h, _ := strconv.ParseFloat(m[1], 64)
		min, _ := strconv.ParseFloat(m[2], 64)
		sec, _ := strconv.ParseFloat(m[3], 64)
		curSec := h*3600 + min*60 + sec
		prog.CurrentSec = curSec
		if totalDuration > 0 {
			pct := (curSec / totalDuration) * 100.0
			if pct > 100.0 {
				pct = 100.0
			}
			prog.Percentage = pct
		}
	}

	return prog
}
